### ISSUE TITLE
Pre-release preparations

### ISSUE THREAD

**Issue by ricardoboss** [microsoft/kiota-dart#52]
First pre-release versions for this project are on the horizon, so I decided to collect remaining tasks before any version can be released.

(order matters!)

- [x] #48
- [x] #54
- [x] #56
- [x] #61
- [x] Transfer [dart_kiota](https://github.com/kiota-community/dart_kiota) to `microsoft` org (and rename to `kiota-dart`)
- [x] Publish initial version manually (@baywet)
- [x] Merge https://github.com/microsoft/kiota/pull/5966
- [x] #46
- [ ] (optional) Test Release workflow on GitHub

**Comment by baywet** [comment]
We can probably add the transfer of this repo to the Microsoft organization to the list.

**Comment by baywet** [comment]
Additionally, we should rename this repo kiota-dart to follow the naming conventions of other languages. If we could do that ahead of the transfer, it'd save us time.

**Comment by ricardoboss** [comment]
Hmm, that would only be possible after the generator PR is merged and the fork deleted because the fork of `ms/kiota` is already called `kiota-dart`...

We could also rename the fork ahead of time, then rename this repo, then do the transfer.

**Comment by baywet** [comment]
Thanks for all the updates today @ricardoboss !
I think we're good for a transfer, adding a task for next week on my side.

**Comment by baywet** [comment]
Update: repo is transferred and initial publish is done https://github.com/microsoft/kiota-dart/releases/tag/v0.0.1
I also setup permissions on the packages to be published by GHA.
The workflow seem to be failing for now.
https://github.com/microsoft/kiota-dart/actions/runs/12634749936

We should also move to create the PR to the upstream kiota repo (generation) and attempt to make it on time for the next minor release (on the 9th)

**Comment by ricardoboss** [comment]
All items are done now. The next release of Kiota will have initial support for generating Dart code. Closing this issue now.
